version: 0.0
os: linux
files:
  - source: /index.html
    source: /style.css
    source: /script.js
    destination: /var/www/html/
    destination: /var/www/css/
    destination: /var/www/js/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
